FROM alpine:3.10.3

# S2I Environment variables
ENV STI_SCRIPTS_PATH=/usr/libexec/s2i \
  APP_ROOT=/opt/app-root \
  HOME=/opt/app-root/src \
  PATH=/opt/app-root/src/bin:/opt/app-root/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin:$PATH \
  BUILDER_VERSION=1.0

LABEL io.k8s.description="Platform for building Spring Boot applications with maven" \
  io.k8s.display-name="Spring Boot builder 1.0" \
  io.openshift.expose-services="8080:http" \
  io.openshift.tags="Java,Springboot,builder" \
  io.openshift.s2i.scripts-url="image://$STI_SCRIPTS_PATH" \
  io.s2i.scripts-url="image://$STI_SCRIPTS_PATH" \
  name="s2i-java-maven"

WORKDIR ${HOME}

# Prepare directories
RUN mkdir /opt/usr && \
  mkdir -p $APP_ROOT && \
  mkdir -p $HOME && \
  mkdir -p $HOME/.npm-global && \
  mkdir -p $STI_SCRIPTS_PATH && \
  mkdir -p /opt/openshift

# Basic install
RUN apk update && apk upgrade && apk add --no-cache \
  bash curl ca-certificates openssl tar git unzip openjdk8 && \
  rm -rf /var/cache/apk/*

# Copy s2i scripts
COPY ./s2i/bin/ $STI_SCRIPTS_PATH

ENV BASH_ENV=$APP_ROOT/etc/scl_enable \
  ENV=$APP_ROOT/etc/scl_enable \
  PROMPT_COMMAND=". $APP_ROOT/etc/scl_enable"

RUN adduser -u 1001 -S -G root -h ${HOME} -s /sbin/nologin default && \
  chown -R 1001:0 $APP_ROOT && \
  chown -R 1001:0 $STI_SCRIPTS_PATH && \
  chown -R 1001:0 /opt/usr && \
  chown -R 1001:0 /opt/openshift

# Maven install
ENV MAVEN_VERSION 3.6.1
RUN (curl -fsSL https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | \
  tar -zx -C /usr/local) && \
  mv /usr/local/apache-maven-$MAVEN_VERSION /usr/local/maven && \
  ln -sf /usr/local/maven/bin/mvn /usr/local/bin/mvn && \
  mkdir -p $HOME/.m2 && chmod -R a+rwX $HOME/.m2

ENV PATH=/usr/local/bin/mvn:$PATH

USER 1001

EXPOSE 8080

CMD $STI_SCRIPTS_PATH/usage